spring:
  application:
    name: credits-core
  
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/bcredits}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASS:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:  # ← Añade configuración de pool
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}  
    show-sql: ${SHOW_SQL:true}      
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect  
        jdbc:
          batch_size: 20  
        order_inserts: true
        order_updates: true
    open-in-view: false

  
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true  # Solo en dev
    time-zone: UTC
    default-property-inclusion: non_null  

credit:
  auto-eval:
    max-amount: ${MAX_CREDIT_AMOUNT:50000.00}  

logging:
  level:
    com.bcredits: ${LOG_LEVEL:DEBUG}
    org.springframework.web: INFO
    org.hibernate.SQL: ${SQL_LOG:DEBUG}
    org.hibernate.orm.jdbc.bind: TRACE

server:
  port: ${PORT:8080}
  error:
    include-message: always  
    include-binding-errors: always